# Quotes and Paraphrases {.unnumbered}

# Fri Jul 21 02:27:35 KST 2022

## 일반적인 질문 (생각나는 대로)

- What is : (definition)
    - human resource analytics
    - people analytics
    - workplace analytics
    - learning analytics
    - computational social science
    - marketing analytics
    - audit analysis
    - business Analytics
- What is the charteristics of analytics
- What is the simiarlirty of the analytics
- What is difference between analytics
- What is main frame(core/idea) of the analytics

## HRD master class에서의 질문

- What do we mean by Data Analytics
    - how it is defined and how does our understanding of the term vary around the world?
- What’s the relationship between Data Analytics and the concepts of work and the workplace?  
    - how has that relationship changed over the years?
- What’s the connection between Data Analytics and HRD? 
    - How does research, theory and practice in one influence research, theory and practice in the other?
- If we look at the challenges facing HRD in organizations over the next few years, how does Data Analytics help HRD in understanding those challenges and working on them?
- What do we mean by Data Analytics 
    - how is it defined and how does our understanding of the term vary around the world? 
- What’s the relationship between Data Analytics and the concepts of work and the workplace? 
    - how has that relationship changed over the years?
- What’s the connection between Data Analytics and HRD? 
    - how does research, theory and practice in one influence research, theory and practice in the other?
- If we look at the challenges facing HRD in organizations over the next few years, how does Data Analytics help HRD in understanding those challenges and working on them?
- I’m wondering what happens if HRD takes a more data analytics approach to addressing organizational challenges 
    - to pick on one for an example, if we consider how best to help employees to learn from each other especially with employees working remotely or in hybrid forms, 
    - how can data analytics help HRD to address that challenge?
- Within organizations, what HRD questions could you see data analytics answering in the coming years that, in most organizations, currently go unanswered?
- Earlier in the episode, you mentioned leveraging data that already exists within organizations – for a typical organization, what existing data could HRD use and where does that data reside?
- What advice do you have for HRD professionals who want to learn how to do data analytics 
    - how to learn the basics of data analysis and what tools to use?
- What advice do you have on how HRD professionals could tap into data experts working within organizations 
    - what job titles might those people have, and are there any best practices around how to work with them?

## TWS세션에서의 질문
- 먼저 HRA/PA란 무엇인지 더 명확하게 알고싶습니다
    - HRA/PA이란 무엇을 의미합니까? 
    - HRD 분야 연구/ 실무 측면에서HRA/PA 에 대한 이해 및 활용이왜 중요할까요? 
    - HRD 입장에서 조직의 어떤 문제들을 해결해 줄까요?
- 현재까지 학계와 현장에서는얼마나 활용되고 발전해 왔는지 궁금합니다.
    - 먼저 연구 측면에서는 현재까지 어떤 발전/변화가 있었나요? 
    - HRD 분야에서는 연구가 이루어 지고 있나요?
- 또 실무에서 HRD가 현장의 문제를 해결하기 위해 더 많은 데이터 분석 접근 방식을 취하면 어떻게 될지 궁금합니다. 
    - HRD 현장/실무에서는 어느 정도 도입 및 활용이 되고 있나요?
    - 현장에서의 HRA/PA 적용 사례(Best Practice)가 있을까요?
- 그렇다면 당장 HRD 실무자들이 HRA/PA 도입 및 활용을 위해 무엇을 할 수 있을지 궁급합니다.  
    - HRD에서 당장 사용할 수 있는 기존 데이터는 무엇이 있고 어떻게 활용 가능한지? 
    - 어떤 결과를 기대 할 수 있는지?
    - 조직 내 타부서 또는 외부 데이터 전문가를 활용할 수 있는 방법도 있을까요?
- 마지막으로 앞으로의 방향성 그리고 HRD 실무자에게 주는 조언에 대해 여쭙고 싶습니다. 
    - HRA/PA에 대한 전망과 HRD에 주는 시사점은 무엇인지?
    - 앞으로 HRA/PA를도입 하고자 하는 HRD 전문가에게 해주고 싶은 조언

## 리터리쳐들에서 도출된 질문들
- 



